### PR TITLE
Patching/Upgrading Vulnerable NPM Dependencies

### PR DESCRIPTION
**Pull request by gamontal**
A recent NPM Audit scan reported over 70 different vulnerabilities from Moderate to Critical categories. Most of them were resolved via package upgrades, but a few others like webpack and typings required additional config modifications. This PR also removes the dependency on [Typings](https://www.npmjs.com/package/typings) which is no longer supported and is vulnerable to [Machine-In-The-Middle](https://github.com/advisories/GHSA-pc5p-h8pf-mvwp) and [Denial of Service](https://github.com/advisories/GHSA-8g7p-74h8-hg48) attacks.

### CODE REVIEW

**Comment by gamontal** [comment]
Hi @obvioussean - Reaching out to you since you were the last to review and merge a PR in this project :). I've successfully tested these changes in private org. Please let me know if you have any questions or concerns. Thanks!

**Comment by obvioussean** [comment]
@gamontal this looks fine but since I'm no longer involved with the team, I'm hesitant to approve it.  @micarls may be a more appropriate approver at this point.

**Comment by gamontal** [comment]
Thanks for reviewing and pointing me to the right contact @obvioussean! @micarls Please let me know if you have any questions or concerns.

**Comment by MOlausson** [comment]
@gamontal @obvioussean @micarls I'll take a look at this. I'm part of the team taking over support for this and a bunch of other MS DevLabs extensions (see https://devblogs.microsoft.com/devops/azure-boards-fall-update/). We're starting a general overhaul of the extensions to release updates with patching and fixes to the most asked for fixes/features. Stay tuned for more updates!

**Comment by MOlausson** [comment]
@gamontal agree with @obvioussean, this looks good. Thanks for your contribution.

**Comment by MOlausson** [comment]
@gamontal we're going to release an update after it's been tested on Azure DevOps server as well.

**Comment by gamontal** [comment]
Hello @MOlausson, thanks again for giving context into the support/ownership changes for this project and merging my patches. I was wondering if there is an established ETA to get this extension updated and published to the Marketplace?

**Pull request merged**
